### ISSUE TITLE
Paper screaming about API versions. (Refusing to load)

### ISSUE THREAD

**Issue by ParadauxDev** [ParadauxDev/HiberniaDiscord#13]
> [01:49:15 ERROR]: Could not load 'plugins/HiberniaDiscord-2.0.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.14
at org.bukkit.craftbukkit.v1_13_R2.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:226) ~[patched_1.13.2.jar:git-Paper-627]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130) ~[patched_1.13.2.jar:git-Paper-627]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[patched_1.13.2.jar:git-Paper-627]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:255) ~[patched_1.13.2.jar:git-Paper-627]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331) ~[patched_1.13.2.jar:git-Paper-627]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-627]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-627]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

This error seems to be localised to only PaperMC. Will release a patch by switching the API-version to 1.13

**Comment by ParadauxDev** [comment]
Fixed in 2.0.1 coming out soon.
